// Generates a clean order/job sheet PDF — full order details for internal use or sharing
// with a customer. Distinct from the GST invoice (lib/invoicePdf.js), which is for billing.

export function generateOrderPDF({ order, material }) {
  return import('jspdf').then(({ default: jsPDF }) => {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 40;
    let y = 50;

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(21, 24, 28);
    doc.text('ORDER DETAILS', margin, y);
    y += 10;

    doc.setDrawColor(232, 98, 44);
    doc.setLineWidth(2.5);
    doc.line(margin, y, margin + 60, y);
    y += 30;

    // Status badge (drawn as a small colored box)
    const statusColors = {
      'Pending': [251, 240, 210],
      'In Progress': [223, 234, 240],
      'Completed': [223, 240, 229],
      'Delayed': [250, 225, 218],
    };
    const statusTextColors = {
      'Pending': [138, 93, 11],
      'In Progress': [35, 82, 114],
      'Completed': [31, 107, 69],
      'Delayed': [161, 63, 31],
    };
    const [br, bg, bb] = statusColors[order.status] || [240, 240, 240];
    const [tr, tg, tb] = statusTextColors[order.status] || [80, 80, 80];
    doc.setFillColor(br, bg, bb);
    doc.roundedRect(margin, y - 14, 90, 22, 4, 4, 'F');
    doc.setTextColor(tr, tg, tb);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(order.status || 'Pending', margin + 45, y + 1, { align: 'center' });

    doc.setTextColor(120, 120, 120);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Generated ${new Date().toLocaleDateString('en-IN')}`, pageWidth - margin, y + 1, { align: 'right' });
    y += 35;

    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(1);
    doc.line(margin, y, pageWidth - margin, y);
    y += 30;

    // Two-column field layout
    const colGap = 20;
    const colWidth = (pageWidth - margin * 2 - colGap) / 2;
    const leftX = margin;
    const rightX = margin + colWidth + colGap;

    const field = (x, yPos, label, value) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(150, 148, 138);
      doc.text(label.toUpperCase(), x, yPos);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11.5);
      doc.setTextColor(21, 24, 28);
      doc.text(String(value || '—'), x, yPos + 16);
    };

    field(leftX, y, 'Customer', order.customer_name);
    field(rightX, y, 'Item', order.item_name);
    y += 42;

    field(leftX, y, 'Quantity', order.quantity ? `${order.quantity.toLocaleString()} units` : null);
    field(rightX, y, 'Due date', order.due_date ? new Date(order.due_date).toLocaleDateString('en-IN') : null);
    y += 42;

    field(leftX, y, 'Price', order.price ? `Rs. ${Number(order.price).toLocaleString('en-IN')}` : null);
    field(rightX, y, 'Days to complete', order.days_to_complete ? `${order.days_to_complete} days` : null);
    y += 42;

    if (material) {
      field(leftX, y, 'Material', material.name + (material.color ? ` — ${material.color}` : ''));
      field(rightX, y, 'Material per unit', order.material_grams_per_unit ? `${order.material_grams_per_unit}g` : null);
      y += 42;
    }

    if (order.hsn_code) {
      field(leftX, y, 'HSN code', order.hsn_code);
      field(rightX, y, 'GST rate', order.gst_rate ? `${order.gst_rate}%` : null);
      y += 42;
    }

    if (order.description) {
      y += 8;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(150, 148, 138);
      doc.text('DESCRIPTION', leftX, y);
      y += 16;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10.5);
      doc.setTextColor(60, 58, 52);
      const descLines = doc.splitTextToSize(order.description, pageWidth - margin * 2);
      doc.text(descLines, leftX, y);
      y += descLines.length * 14 + 20;
    }

    if (order.notes) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(150, 148, 138);
      doc.text('NOTES', leftX, y);
      y += 16;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10.5);
      doc.setTextColor(60, 58, 52);
      const noteLines = doc.splitTextToSize(order.notes, pageWidth - margin * 2);
      doc.text(noteLines, leftX, y);
      y += noteLines.length * 14 + 10;
    }

    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text('Generated by PlastiFlow', margin, doc.internal.pageSize.getHeight() - 30);

    return doc;
  });
}
